export const codes = {
  AF: "93",
  AX: "358",
  AL: "355",
  DZ: "213",
  AS: "1-684",
  AD: "376",
  AO: "244",
  AI: "1-264",
  AQ: "672",
  AG: "1-268",
  AR: "54",
  AM: "374",
  AW: "297",
  AU: "61",
  AT: "43",
  AZ: "994",
  BS: "1-242",
  BH: "973",
  BD: "880",
  BB: "1-246",
  BY: "375",
  BE: "32",
  BZ: "501",
  BJ: "229",
  BM: "1-441",
  BT: "975",
  BO: "591",
  BA: "387",
  BW: "267",
  BV: "47",
  BR: "55",
  IO: "246",
  VG: "1-284",
  BN: "673",
  BG: "359",
  BF: "226",
  BI: "257",
  KH: "855",
  CM: "237",
  CA: "1",
  CV: "238",
  KY: "1-345",
  CF: "236",
  TD: "235",
  CL: "56",
  CN: "86",
  CX: "61",
  CC: "61",
  CO: "57",
  KM: "269",
  CK: "682",
  CR: "506",
  HR: "385",
  CU: "53",
  CW: "599",
  CY: "357",
  CZ: "420",
  CD: "243",
  DK: "45",
  DJ: "253",
  DM: "1-767",
  DO: "1-809",
  TL: "670",
  EC: "593",
  EG: "20",
  SV: "503",
  GQ: "240",
  ER: "291",
  EE: "372",
  ET: "251",
  FK: "500",
  FO: "298",
  FJ: "679",
  FI: "358",
  FR: "33",
  GF: "594",
  PF: "689",
  TF: "262",
  GA: "241",
  GM: "220",
  GE: "995",
  DE: "49",
  GH: "233",
  GI: "350",
  GR: "30",
  GL: "299",
  GD: "1-473",
  GP: "590",
  GU: "1-671",
  GT: "502",
  GG: "44",
  GN: "224",
  GW: "245",
  GY: "592",
  HT: "509",
  HM: "672",
  HN: "504",
  HK: "852",
  HU: "36",
  IS: "354",
  IN: "91",
  ID: "62",
  IR: "98",
  IQ: "964",
  IE: "353",
  IM: "44",
  IL: "972",
  IT: "39",
  CI: "225",
  JM: "1-876",
  JP: "81",
  JE: "44",
  JO: "962",
  KZ: "7",
  KE: "254",
  KI: "686",
  XK: "383",
  KW: "965",
  KG: "996",
  LA: "856",
  LV: "371",
  LB: "961",
  LS: "266",
  LR: "231",
  LY: "218",
  LI: "423",
  LT: "370",
  LU: "352",
  MO: "853",
  MK: "389",
  MG: "261",
  MW: "265",
  MY: "60",
  MV: "960",
  ML: "223",
  MT: "356",
  MH: "692",
  MQ: "596",
  MR: "222",
  MU: "230",
  YT: "262",
  MX: "52",
  FM: "691",
  MD: "373",
  MC: "377",
  MN: "976",
  ME: "382",
  MS: "1-664",
  MA: "212",
  MZ: "258",
  MM: "95",
  NA: "264",
  NR: "674",
  NP: "977",
  NL: "31",
  AN: "599",
  NC: "687",
  NZ: "64",
  NI: "505",
  NE: "227",
  NG: "234",
  NU: "683",
  NF: "672",
  KP: "850",
  MP: "1-670",
  NO: "47",
  OM: "968",
  PK: "92",
  PW: "680",
  PS: "970",
  PA: "507",
  PG: "675",
  PY: "595",
  PE: "51",
  PH: "63",
  PN: "64",
  PL: "48",
  PT: "351",
  QA: "974",
  RE: "262",
  RO: "40",
  RU: "7",
  RW: "250",
  BL: "590",
  SH: "290",
  KN: "1-869",
  LC: "1-758",
  MF: "590",
  PM: "508",
  VC: "1-784",
  WS: "685",
  SM: "378",
  ST: "239",
  SA: "966",
  SN: "221",
  RS: "381",
  SC: "248",
  SL: "232",
  SG: "65",
  SX: "1-721",
  SK: "421",
  SI: "386",
  SB: "677",
  SO: "252",
  ZA: "27",
  KR: "82",
  SS: "211",
  ES: "34",
  LK: "94",
  SD: "249",
  SR: "597",
  SJ: "47",
  SZ: "268",
  SE: "46",
  CH: "41",
  SY: "963",
  TW: "886",
  TJ: "992",
  TZ: "255",
  TH: "66",
  TG: "228",
  TK: "690",
  TO: "676",
  TT: "1-868",
  TN: "216",
  TR: "90",
  TM: "993",
  TC: "1-649",
  TV: "688",
  VI: "1-340",
  UG: "256",
  UA: "380",
  AE: "971",
  GB: "44",
  US: "1",
  UY: "598",
  UZ: "998",
  VU: "678",
  VA: "379",
  VE: "58",
  VN: "84",
  WF: "681",
  EH: "212",
  YE: "967",
  ZM: "260",
  ZW: "263",
};

export const data = [
  {
    name: "Afghanistan",
    dial_code: "+93",
    code: "AF",
    ccode: "93",
    show: "AF(+93)",
  },
  {
    name: "Aland Islands",
    dial_code: "+358",
    code: "AX",
    ccode: "358",
    show: "AX(+358)",
  },
  {
    name: "Albania",
    dial_code: "+355",
    code: "AL",
    ccode: "355",
    show: "AL(+355)",
  },
  {
    name: "Algeria",
    dial_code: "+213",
    code: "DZ",
    ccode: "213",
    show: "DZ(+213)",
  },
  {
    name: "AmericanSamoa",
    dial_code: "+1684",
    code: "AS",
    ccode: "1684",
    show: "AS(+1684)",
  },
  {
    name: "Andorra",
    dial_code: "+376",
    code: "AD",
    ccode: "376",
    show: "AD(+376)",
  },
  {
    name: "Angola",
    dial_code: "+244",
    code: "AO",
    ccode: "244",
    show: "AO(+244)",
  },
  {
    name: "Anguilla",
    dial_code: "+1264",
    code: "AI",
    ccode: "1264",
    show: "AI(+1264)",
  },
  {
    name: "Antarctica",
    dial_code: "+672",
    code: "AQ",
    ccode: "672",
    show: "AQ(+672)",
  },
  {
    name: "Antigua and Barbuda",
    dial_code: "+1268",
    code: "AG",
    ccode: "1268",
    show: "AG(+1268)",
  },
  {
    name: "Argentina",
    dial_code: "+54",
    code: "AR",
    ccode: "54",
    show: "AR(+54)",
  },
  {
    name: "Armenia",
    dial_code: "+374",
    code: "AM",
    ccode: "374",
    show: "AM(+374)",
  },
  {
    name: "Aruba",
    dial_code: "+297",
    code: "AW",
    ccode: "297",
    show: "AW(+297)",
  },
  {
    name: "Australia",
    dial_code: "+61",
    code: "AU",
    ccode: "61",
    show: "AU(+61)",
  },
  {
    name: "Austria",
    dial_code: "+43",
    code: "AT",
    ccode: "43",
    show: "AT(+43)",
  },
  {
    name: "Azerbaijan",
    dial_code: "+994",
    code: "AZ",
    ccode: "994",
    show: "AZ(+994)",
  },
  {
    name: "Bahamas",
    dial_code: "+1242",
    code: "BS",
    ccode: "1242",
    show: "BS(+1242)",
  },
  {
    name: "Bahrain",
    dial_code: "+973",
    code: "BH",
    ccode: "973",
    show: "BH(+973)",
  },
  {
    name: "Bangladesh",
    dial_code: "+880",
    code: "BD",
    ccode: "880",
    show: "BD(+880)",
  },
  {
    name: "Barbados",
    dial_code: "+1246",
    code: "BB",
    ccode: "1246",
    show: "BB(+1246)",
  },
  {
    name: "Belarus",
    dial_code: "+375",
    code: "BY",
    ccode: "375",
    show: "BY(+375)",
  },
  {
    name: "Belgium",
    dial_code: "+32",
    code: "BE",
    ccode: "32",
    show: "BE(+32)",
  },
  {
    name: "Belize",
    dial_code: "+501",
    code: "BZ",
    ccode: "501",
    show: "BZ(+501)",
  },
  {
    name: "Benin",
    dial_code: "+229",
    code: "BJ",
    ccode: "229",
    show: "BJ(+229)",
  },
  {
    name: "Bermuda",
    dial_code: "+1441",
    code: "BM",
    ccode: "1441",
    show: "BM(+1441)",
  },
  {
    name: "Bhutan",
    dial_code: "+975",
    code: "BT",
    ccode: "975",
    show: "BT(+975)",
  },
  {
    name: "Bolivia, Plurinational State of",
    dial_code: "+591",
    code: "BO",
    ccode: "591",
    show: "BO(+591)",
  },
  {
    name: "Bosnia and Herzegovina",
    dial_code: "+387",
    code: "BA",
    ccode: "387",
    show: "BA(+387)",
  },
  {
    name: "Botswana",
    dial_code: "+267",
    code: "BW",
    ccode: "267",
    show: "BW(+267)",
  },
  {
    name: "Brazil",
    dial_code: "+55",
    code: "BR",
    ccode: "55",
    show: "BR(+55)",
  },
  {
    name: "British Indian Ocean Territory",
    dial_code: "+246",
    code: "IO",
    ccode: "246",
    show: "IO(+246)",
  },
  {
    name: "Brunei Darussalam",
    dial_code: "+673",
    code: "BN",
    ccode: "673",
    show: "BN(+673)",
  },
  {
    name: "Bulgaria",
    dial_code: "+359",
    code: "BG",
    ccode: "359",
    show: "BG(+359)",
  },
  {
    name: "Burkina Faso",
    dial_code: "+226",
    code: "BF",
    ccode: "226",
    show: "BF(+226)",
  },
  {
    name: "Burundi",
    dial_code: "+257",
    code: "BI",
    ccode: "257",
    show: "BI(+257)",
  },
  {
    name: "Cambodia",
    dial_code: "+855",
    code: "KH",
    ccode: "855",
    show: "KH(+855)",
  },
  {
    name: "Cameroon",
    dial_code: "+237",
    code: "CM",
    ccode: "237",
    show: "CM(+237)",
  },
  {
    name: "Canada",
    dial_code: "+1",
    code: "CA",
    ccode: "1",
    show: "CA(+1)",
  },
  {
    name: "Cape Verde",
    dial_code: "+238",
    code: "CV",
    ccode: "238",
    show: "CV(+238)",
  },
  {
    name: "Cayman Islands",
    dial_code: "+345",
    code: "KY",
    ccode: "345",
    show: "KY(+345)",
  },
  {
    name: "Central African Republic",
    dial_code: "+236",
    code: "CF",
    ccode: "236",
    show: "CF(+236)",
  },
  {
    name: "Chad",
    dial_code: "+235",
    code: "TD",
    ccode: "235",
    show: "TD(+235)",
  },
  {
    name: "Chile",
    dial_code: "+56",
    code: "CL",
    ccode: "56",
    show: "CL(+56)",
  },
  {
    name: "China",
    dial_code: "+86",
    code: "CN",
    ccode: "86",
    show: "CN(+86)",
  },
  {
    name: "Christmas Island",
    dial_code: "+61",
    code: "CX",
    ccode: "61",
    show: "CX(+61)",
  },
  {
    name: "Cocos (Keeling) Islands",
    dial_code: "+61",
    code: "CC",
    ccode: "61",
    show: "CC(+61)",
  },
  {
    name: "Colombia",
    dial_code: "+57",
    code: "CO",
    ccode: "57",
    show: "CO(+57)",
  },
  {
    name: "Comoros",
    dial_code: "+269",
    code: "KM",
    ccode: "269",
    show: "KM(+269)",
  },
  {
    name: "Congo",
    dial_code: "+242",
    code: "CG",
    ccode: "242",
    show: "CG(+242)",
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dial_code: "+243",
    code: "CD",
    ccode: "243",
    show: "CD(+243)",
  },
  {
    name: "Cook Islands",
    dial_code: "+682",
    code: "CK",
    ccode: "682",
    show: "CK(+682)",
  },
  {
    name: "Costa Rica",
    dial_code: "+506",
    code: "CR",
    ccode: "506",
    show: "CR(+506)",
  },
  {
    name: "Cote d'Ivoire",
    dial_code: "+225",
    code: "CI",
    ccode: "225",
    show: "CI(+225)",
  },
  {
    name: "Croatia",
    dial_code: "+385",
    code: "HR",
    ccode: "385",
    show: "HR(+385)",
  },
  {
    name: "Cuba",
    dial_code: "+53",
    code: "CU",
    ccode: "53",
    show: "CU(+53)",
  },
  {
    name: "Cyprus",
    dial_code: "+357",
    code: "CY",
    ccode: "357",
    show: "CY(+357)",
  },
  {
    name: "Czech Republic",
    dial_code: "+420",
    code: "CZ",
    ccode: "420",
    show: "CZ(+420)",
  },
  {
    name: "Denmark",
    dial_code: "+45",
    code: "DK",
    ccode: "45",
    show: "DK(+45)",
  },
  {
    name: "Djibouti",
    dial_code: "+253",
    code: "DJ",
    ccode: "253",
    show: "DJ(+253)",
  },
  {
    name: "Dominica",
    dial_code: "+1767",
    code: "DM",
    ccode: "1767",
    show: "DM(+1767)",
  },
  {
    name: "Dominican Republic",
    dial_code: "+1849",
    code: "DO",
    ccode: "1849",
    show: "DO(+1849)",
  },
  {
    name: "Ecuador",
    dial_code: "+593",
    code: "EC",
    ccode: "593",
    show: "EC(+593)",
  },
  {
    name: "Egypt",
    dial_code: "+20",
    code: "EG",
    ccode: "20",
    show: "EG(+20)",
  },
  {
    name: "El Salvador",
    dial_code: "+503",
    code: "SV",
    ccode: "503",
    show: "SV(+503)",
  },
  {
    name: "Equatorial Guinea",
    dial_code: "+240",
    code: "GQ",
    ccode: "240",
    show: "GQ(+240)",
  },
  {
    name: "Eritrea",
    dial_code: "+291",
    code: "ER",
    ccode: "291",
    show: "ER(+291)",
  },
  {
    name: "Estonia",
    dial_code: "+372",
    code: "EE",
    ccode: "372",
    show: "EE(+372)",
  },
  {
    name: "Ethiopia",
    dial_code: "+251",
    code: "ET",
    ccode: "251",
    show: "ET(+251)",
  },
  {
    name: "Falkland Islands (Malvinas)",
    dial_code: "+500",
    code: "FK",
    ccode: "500",
    show: "FK(+500)",
  },
  {
    name: "Faroe Islands",
    dial_code: "+298",
    code: "FO",
    ccode: "298",
    show: "FO(+298)",
  },
  {
    name: "Fiji",
    dial_code: "+679",
    code: "FJ",
    ccode: "679",
    show: "FJ(+679)",
  },
  {
    name: "Finland",
    dial_code: "+358",
    code: "FI",
    ccode: "358",
    show: "FI(+358)",
  },
  {
    name: "France",
    dial_code: "+33",
    code: "FR",
    ccode: "33",
    show: "FR(+33)",
  },
  {
    name: "French Guiana",
    dial_code: "+594",
    code: "GF",
    ccode: "594",
    show: "GF(+594)",
  },
  {
    name: "French Polynesia",
    dial_code: "+689",
    code: "PF",
    ccode: "689",
    show: "PF(+689)",
  },
  {
    name: "Gabon",
    dial_code: "+241",
    code: "GA",
    ccode: "241",
    show: "GA(+241)",
  },
  {
    name: "Gambia",
    dial_code: "+220",
    code: "GM",
    ccode: "220",
    show: "GM(+220)",
  },
  {
    name: "Georgia",
    dial_code: "+995",
    code: "GE",
    ccode: "995",
    show: "GE(+995)",
  },
  {
    name: "Germany",
    dial_code: "+49",
    code: "DE",
    ccode: "49",
    show: "DE(+49)",
  },
  {
    name: "Ghana",
    dial_code: "+233",
    code: "GH",
    ccode: "233",
    show: "GH(+233)",
  },
  {
    name: "Gibraltar",
    dial_code: "+350",
    code: "GI",
    ccode: "350",
    show: "GI(+350)",
  },
  {
    name: "Greece",
    dial_code: "+30",
    code: "GR",
    ccode: "30",
    show: "GR(+30)",
  },
  {
    name: "Greenland",
    dial_code: "+299",
    code: "GL",
    ccode: "299",
    show: "GL(+299)",
  },
  {
    name: "Grenada",
    dial_code: "+1473",
    code: "GD",
    ccode: "1473",
    show: "GD(+1473)",
  },
  {
    name: "Guadeloupe",
    dial_code: "+590",
    code: "GP",
    ccode: "590",
    show: "GP(+590)",
  },
  {
    name: "Guam",
    dial_code: "+1671",
    code: "GU",
    ccode: "1671",
    show: "GU(+1671)",
  },
  {
    name: "Guatemala",
    dial_code: "+502",
    code: "GT",
    ccode: "502",
    show: "GT(+502)",
  },
  {
    name: "Guernsey",
    dial_code: "+44",
    code: "GG",
    ccode: "44",
    show: "GG(+44)",
  },
  {
    name: "Guinea",
    dial_code: "+224",
    code: "GN",
    ccode: "224",
    show: "GN(+224)",
  },
  {
    name: "Guinea-Bissau",
    dial_code: "+245",
    code: "GW",
    ccode: "245",
    show: "GW(+245)",
  },
  {
    name: "Guyana",
    dial_code: "+595",
    code: "GY",
    ccode: "595",
    show: "GY(+595)",
  },
  {
    name: "Haiti",
    dial_code: "+509",
    code: "HT",
    ccode: "509",
    show: "HT(+509)",
  },
  {
    name: "Holy See (Vatican City State)",
    dial_code: "+379",
    code: "VA",
    ccode: "379",
    show: "VA(+379)",
  },
  {
    name: "Honduras",
    dial_code: "+504",
    code: "HN",
    ccode: "504",
    show: "HN(+504)",
  },
  {
    name: "Hong Kong",
    dial_code: "+852",
    code: "HK",
    ccode: "852",
    show: "HK(+852)",
  },
  {
    name: "Hungary",
    dial_code: "+36",
    code: "HU",
    ccode: "36",
    show: "HU(+36)",
  },
  {
    name: "Iceland",
    dial_code: "+354",
    code: "IS",
    ccode: "354",
    show: "IS(+354)",
  },
  {
    name: "India",
    dial_code: "+91",
    code: "IN",
    ccode: "91",
    show: "IN(+91)",
  },
  {
    name: "Indonesia",
    dial_code: "+62",
    code: "ID",
    ccode: "62",
    show: "ID(+62)",
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    dial_code: "+98",
    code: "IR",
    ccode: "98",
    show: "IR(+98)",
  },
  {
    name: "Iraq",
    dial_code: "+964",
    code: "IQ",
    ccode: "964",
    show: "IQ(+964)",
  },
  {
    name: "Ireland",
    dial_code: "+353",
    code: "IE",
    ccode: "353",
    show: "IE(+353)",
  },
  {
    name: "Isle of Man",
    dial_code: "+44",
    code: "IM",
    ccode: "44",
    show: "IM(+44)",
  },
  {
    name: "Israel",
    dial_code: "+972",
    code: "IL",
    ccode: "972",
    show: "IL(+972)",
  },
  {
    name: "Italy",
    dial_code: "+39",
    code: "IT",
    ccode: "39",
    show: "IT(+39)",
  },
  {
    name: "Jamaica",
    dial_code: "+1876",
    code: "JM",
    ccode: "1876",
    show: "JM(+1876)",
  },
  {
    name: "Japan",
    dial_code: "+81",
    code: "JP",
    ccode: "81",
    show: "JP(+81)",
  },
  {
    name: "Jersey",
    dial_code: "+44",
    code: "JE",
    ccode: "44",
    show: "JE(+44)",
  },
  {
    name: "Jordan",
    dial_code: "+962",
    code: "JO",
    ccode: "962",
    show: "JO(+962)",
  },
  {
    name: "Kazakhstan",
    dial_code: "+77",
    code: "KZ",
    ccode: "77",
    show: "KZ(+77)",
  },
  {
    name: "Kenya",
    dial_code: "+254",
    code: "KE",
    ccode: "254",
    show: "KE(+254)",
  },
  {
    name: "Kiribati",
    dial_code: "+686",
    code: "KI",
    ccode: "686",
    show: "KI(+686)",
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: "+850",
    code: "KP",
    ccode: "850",
    show: "KP(+850)",
  },
  {
    name: "Korea, Republic of South Korea",
    dial_code: "+82",
    code: "KR",
    ccode: "82",
    show: "KR(+82)",
  },
  {
    name: "Kuwait",
    dial_code: "+965",
    code: "KW",
    ccode: "965",
    show: "KW(+965)",
  },
  {
    name: "Kyrgyzstan",
    dial_code: "+996",
    code: "KG",
    ccode: "996",
    show: "KG(+996)",
  },
  {
    name: "Laos",
    dial_code: "+856",
    code: "LA",
    ccode: "856",
    show: "LA(+856)",
  },
  {
    name: "Latvia",
    dial_code: "+371",
    code: "LV",
    ccode: "371",
    show: "LV(+371)",
  },
  {
    name: "Lebanon",
    dial_code: "+961",
    code: "LB",
    ccode: "961",
    show: "LB(+961)",
  },
  {
    name: "Lesotho",
    dial_code: "+266",
    code: "LS",
    ccode: "266",
    show: "LS(+266)",
  },
  {
    name: "Liberia",
    dial_code: "+231",
    code: "LR",
    ccode: "231",
    show: "LR(+231)",
  },
  {
    name: "Libyan Arab Jamahiriya",
    dial_code: "+218",
    code: "LY",
    ccode: "218",
    show: "LY(+218)",
  },
  {
    name: "Liechtenstein",
    dial_code: "+423",
    code: "LI",
    ccode: "423",
    show: "LI(+423)",
  },
  {
    name: "Lithuania",
    dial_code: "+370",
    code: "LT",
    ccode: "370",
    show: "LT(+370)",
  },
  {
    name: "Luxembourg",
    dial_code: "+352",
    code: "LU",
    ccode: "352",
    show: "LU(+352)",
  },
  {
    name: "Macao",
    dial_code: "+853",
    code: "MO",
    ccode: "853",
    show: "MO(+853)",
  },
  {
    name: "Macedonia",
    dial_code: "+389",
    code: "MK",
    ccode: "389",
    show: "MK(+389)",
  },
  {
    name: "Madagascar",
    dial_code: "+261",
    code: "MG",
    ccode: "261",
    show: "MG(+261)",
  },
  {
    name: "Malawi",
    dial_code: "+265",
    code: "MW",
    ccode: "265",
    show: "MW(+265)",
  },
  {
    name: "Malaysia",
    dial_code: "+60",
    code: "MY",
    ccode: "60",
    show: "MY(+60)",
  },
  {
    name: "Maldives",
    dial_code: "+960",
    code: "MV",
    ccode: "960",
    show: "MV(+960)",
  },
  {
    name: "Mali",
    dial_code: "+223",
    code: "ML",
    ccode: "223",
    show: "ML(+223)",
  },
  {
    name: "Malta",
    dial_code: "+356",
    code: "MT",
    ccode: "356",
    show: "MT(+356)",
  },
  {
    name: "Marshall Islands",
    dial_code: "+692",
    code: "MH",
    ccode: "692",
    show: "MH(+692)",
  },
  {
    name: "Martinique",
    dial_code: "+596",
    code: "MQ",
    ccode: "596",
    show: "MQ(+596)",
  },
  {
    name: "Mauritania",
    dial_code: "+222",
    code: "MR",
    ccode: "222",
    show: "MR(+222)",
  },
  {
    name: "Mauritius",
    dial_code: "+230",
    code: "MU",
    ccode: "230",
    show: "MU(+230)",
  },
  {
    name: "Mayotte",
    dial_code: "+262",
    code: "YT",
    ccode: "262",
    show: "YT(+262)",
  },
  {
    name: "Mexico",
    dial_code: "+52",
    code: "MX",
    ccode: "52",
    show: "MX(+52)",
  },
  {
    name: "Micronesia, Federated States of Micronesia",
    dial_code: "+691",
    code: "FM",
    ccode: "691",
    show: "FM(+691)",
  },
  {
    name: "Moldova",
    dial_code: "+373",
    code: "MD",
    ccode: "373",
    show: "MD(+373)",
  },
  {
    name: "Monaco",
    dial_code: "+377",
    code: "MC",
    ccode: "377",
    show: "MC(+377)",
  },
  {
    name: "Mongolia",
    dial_code: "+976",
    code: "MN",
    ccode: "976",
    show: "MN(+976)",
  },
  {
    name: "Montenegro",
    dial_code: "+382",
    code: "ME",
    ccode: "382",
    show: "ME(+382)",
  },
  {
    name: "Montserrat",
    dial_code: "+1664",
    code: "MS",
    ccode: "1664",
    show: "MS(+1664)",
  },
  {
    name: "Morocco",
    dial_code: "+212",
    code: "MA",
    ccode: "212",
    show: "MA(+212)",
  },
  {
    name: "Mozambique",
    dial_code: "+258",
    code: "MZ",
    ccode: "258",
    show: "MZ(+258)",
  },
  {
    name: "Myanmar",
    dial_code: "+95",
    code: "MM",
    ccode: "95",
    show: "MM(+95)",
  },
  {
    name: "Namibia",
    dial_code: "+264",
    code: "NA",
    ccode: "264",
    show: "NA(+264)",
  },
  {
    name: "Nauru",
    dial_code: "+674",
    code: "NR",
    ccode: "674",
    show: "NR(+674)",
  },
  {
    name: "Nepal",
    dial_code: "+977",
    code: "NP",
    ccode: "977",
    show: "NP(+977)",
  },
  {
    name: "Netherlands",
    dial_code: "+31",
    code: "NL",
    ccode: "31",
    show: "NL(+31)",
  },
  {
    name: "Netherlands Antilles",
    dial_code: "+599",
    code: "AN",
    ccode: "599",
    show: "AN(+599)",
  },
  {
    name: "New Caledonia",
    dial_code: "+687",
    code: "NC",
    ccode: "687",
    show: "NC(+687)",
  },
  {
    name: "New Zealand",
    dial_code: "+64",
    code: "NZ",
    ccode: "64",
    show: "NZ(+64)",
  },
  {
    name: "Nicaragua",
    dial_code: "+505",
    code: "NI",
    ccode: "505",
    show: "NI(+505)",
  },
  {
    name: "Niger",
    dial_code: "+227",
    code: "NE",
    ccode: "227",
    show: "NE(+227)",
  },
  {
    name: "Nigeria",
    dial_code: "+234",
    code: "NG",
    ccode: "234",
    show: "NG(+234)",
  },
  {
    name: "Niue",
    dial_code: "+683",
    code: "NU",
    ccode: "683",
    show: "NU(+683)",
  },
  {
    name: "Norfolk Island",
    dial_code: "+672",
    code: "NF",
    ccode: "672",
    show: "NF(+672)",
  },
  {
    name: "Northern Mariana Islands",
    dial_code: "+1670",
    code: "MP",
    ccode: "1670",
    show: "MP(+1670)",
  },
  {
    name: "Norway",
    dial_code: "+47",
    code: "NO",
    ccode: "47",
    show: "NO(+47)",
  },
  {
    name: "Oman",
    dial_code: "+968",
    code: "OM",
    ccode: "968",
    show: "OM(+968)",
  },
  {
    name: "Pakistan",
    dial_code: "+92",
    code: "PK",
    ccode: "92",
    show: "PK(+92)",
  },
  {
    name: "Palau",
    dial_code: "+680",
    code: "PW",
    ccode: "680",
    show: "PW(+680)",
  },
  {
    name: "Palestinian Territory, Occupied",
    dial_code: "+970",
    code: "PS",
    ccode: "970",
    show: "PS(+970)",
  },
  {
    name: "Panama",
    dial_code: "+507",
    code: "PA",
    ccode: "507",
    show: "PA(+507)",
  },
  {
    name: "Papua New Guinea",
    dial_code: "+675",
    code: "PG",
    ccode: "675",
    show: "PG(+675)",
  },
  {
    name: "Paraguay",
    dial_code: "+595",
    code: "PY",
    ccode: "595",
    show: "PY(+595)",
  },
  {
    name: "Peru",
    dial_code: "+51",
    code: "PE",
    ccode: "51",
    show: "PE(+51)",
  },
  {
    name: "Philippines",
    dial_code: "+63",
    code: "PH",
    ccode: "63",
    show: "PH(+63)",
  },
  {
    name: "Pitcairn",
    dial_code: "+872",
    code: "PN",
    ccode: "872",
    show: "PN(+872)",
  },
  {
    name: "Poland",
    dial_code: "+48",
    code: "PL",
    ccode: "48",
    show: "PL(+48)",
  },
  {
    name: "Portugal",
    dial_code: "+351",
    code: "PT",
    ccode: "351",
    show: "PT(+351)",
  },
  {
    name: "Puerto Rico",
    dial_code: "+1939",
    code: "PR",
    ccode: "1939",
    show: "PR(+1939)",
  },
  {
    name: "Qatar",
    dial_code: "+974",
    code: "QA",
    ccode: "974",
    show: "QA(+974)",
  },
  {
    name: "Romania",
    dial_code: "+40",
    code: "RO",
    ccode: "40",
    show: "RO(+40)",
  },
  {
    name: "Russia",
    dial_code: "+7",
    code: "RU",
    ccode: "7",
    show: "RU(+7)",
  },
  {
    name: "Rwanda",
    dial_code: "+250",
    code: "RW",
    ccode: "250",
    show: "RW(+250)",
  },
  {
    name: "Reunion",
    dial_code: "+262",
    code: "RE",
    ccode: "262",
    show: "RE(+262)",
  },
  {
    name: "Saint Barthelemy",
    dial_code: "+590",
    code: "BL",
    ccode: "590",
    show: "BL(+590)",
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dial_code: "+290",
    code: "SH",
    ccode: "290",
    show: "SH(+290)",
  },
  {
    name: "Saint Kitts and Nevis",
    dial_code: "+1869",
    code: "KN",
    ccode: "1869",
    show: "KN(+1869)",
  },
  {
    name: "Saint Lucia",
    dial_code: "+1758",
    code: "LC",
    ccode: "1758",
    show: "LC(+1758)",
  },
  {
    name: "Saint Martin",
    dial_code: "+590",
    code: "MF",
    ccode: "590",
    show: "MF(+590)",
  },
  {
    name: "Saint Pierre and Miquelon",
    dial_code: "+508",
    code: "PM",
    ccode: "508",
    show: "PM(+508)",
  },
  {
    name: "Saint Vincent and the Grenadines",
    dial_code: "+1784",
    code: "VC",
    ccode: "1784",
    show: "VC(+1784)",
  },
  {
    name: "Samoa",
    dial_code: "+685",
    code: "WS",
    ccode: "685",
    show: "WS(+685)",
  },
  {
    name: "San Marino",
    dial_code: "+378",
    code: "SM",
    ccode: "378",
    show: "SM(+378)",
  },
  {
    name: "Sao Tome and Principe",
    dial_code: "+239",
    code: "ST",
    ccode: "239",
    show: "ST(+239)",
  },
  {
    name: "Saudi Arabia",
    dial_code: "+966",
    code: "SA",
    ccode: "966",
    show: "SA(+966)",
  },
  {
    name: "Senegal",
    dial_code: "+221",
    code: "SN",
    ccode: "221",
    show: "SN(+221)",
  },
  {
    name: "Serbia",
    dial_code: "+381",
    code: "RS",
    ccode: "381",
    show: "RS(+381)",
  },
  {
    name: "Seychelles",
    dial_code: "+248",
    code: "SC",
    ccode: "248",
    show: "SC(+248)",
  },
  {
    name: "Sierra Leone",
    dial_code: "+232",
    code: "SL",
    ccode: "232",
    show: "SL(+232)",
  },
  {
    name: "Singapore",
    dial_code: "+65",
    code: "SG",
    ccode: "65",
    show: "SG(+65)",
  },
  {
    name: "Slovakia",
    dial_code: "+421",
    code: "SK",
    ccode: "421",
    show: "SK(+421)",
  },
  {
    name: "Slovenia",
    dial_code: "+386",
    code: "SI",
    ccode: "386",
    show: "SI(+386)",
  },
  {
    name: "Solomon Islands",
    dial_code: "+677",
    code: "SB",
    ccode: "677",
    show: "SB(+677)",
  },
  {
    name: "Somalia",
    dial_code: "+252",
    code: "SO",
    ccode: "252",
    show: "SO(+252)",
  },
  {
    name: "South Africa",
    dial_code: "+27",
    code: "ZA",
    ccode: "27",
    show: "ZA(+27)",
  },
  {
    name: "South Sudan",
    dial_code: "+211",
    code: "SS",
    ccode: "211",
    show: "SS(+211)",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    dial_code: "+500",
    code: "GS",
    ccode: "500",
    show: "GS(+500)",
  },
  {
    name: "Spain",
    dial_code: "+34",
    code: "ES",
    ccode: "34",
    show: "ES(+34)",
  },
  {
    name: "Sri Lanka",
    dial_code: "+94",
    code: "LK",
    ccode: "94",
    show: "LK(+94)",
  },
  {
    name: "Sudan",
    dial_code: "+249",
    code: "SD",
    ccode: "249",
    show: "SD(+249)",
  },
  {
    name: "Suriname",
    dial_code: "+597",
    code: "SR",
    ccode: "597",
    show: "SR(+597)",
  },
  {
    name: "Svalbard and Jan Mayen",
    dial_code: "+47",
    code: "SJ",
    ccode: "47",
    show: "SJ(+47)",
  },
  {
    name: "Swaziland",
    dial_code: "+268",
    code: "SZ",
    ccode: "268",
    show: "SZ(+268)",
  },
  {
    name: "Sweden",
    dial_code: "+46",
    code: "SE",
    ccode: "46",
    show: "SE(+46)",
  },
  {
    name: "Switzerland",
    dial_code: "+41",
    code: "CH",
    ccode: "41",
    show: "CH(+41)",
  },
  {
    name: "Syrian Arab Republic",
    dial_code: "+963",
    code: "SY",
    ccode: "963",
    show: "SY(+963)",
  },
  {
    name: "Taiwan",
    dial_code: "+886",
    code: "TW",
    ccode: "886",
    show: "TW(+886)",
  },
  {
    name: "Tajikistan",
    dial_code: "+992",
    code: "TJ",
    ccode: "992",
    show: "TJ(+992)",
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    dial_code: "+255",
    code: "TZ",
    ccode: "255",
    show: "TZ(+255)",
  },
  {
    name: "Thailand",
    dial_code: "+66",
    code: "TH",
    ccode: "66",
    show: "TH(+66)",
  },
  {
    name: "Timor-Leste",
    dial_code: "+670",
    code: "TL",
    ccode: "670",
    show: "TL(+670)",
  },
  {
    name: "Togo",
    dial_code: "+228",
    code: "TG",
    ccode: "228",
    show: "TG(+228)",
  },
  {
    name: "Tokelau",
    dial_code: "+690",
    code: "TK",
    ccode: "690",
    show: "TK(+690)",
  },
  {
    name: "Tonga",
    dial_code: "+676",
    code: "TO",
    ccode: "676",
    show: "TO(+676)",
  },
  {
    name: "Trinidad and Tobago",
    dial_code: "+1868",
    code: "TT",
    ccode: "1868",
    show: "TT(+1868)",
  },
  {
    name: "Tunisia",
    dial_code: "+216",
    code: "TN",
    ccode: "216",
    show: "TN(+216)",
  },
  {
    name: "Turkey",
    dial_code: "+90",
    code: "TR",
    ccode: "90",
    show: "TR(+90)",
  },
  {
    name: "Turkmenistan",
    dial_code: "+993",
    code: "TM",
    ccode: "993",
    show: "TM(+993)",
  },
  {
    name: "Turks and Caicos Islands",
    dial_code: "+1649",
    code: "TC",
    ccode: "1649",
    show: "TC(+1649)",
  },
  {
    name: "Tuvalu",
    dial_code: "+688",
    code: "TV",
    ccode: "688",
    show: "TV(+688)",
  },
  {
    name: "Uganda",
    dial_code: "+256",
    code: "UG",
    ccode: "256",
    show: "UG(+256)",
  },
  {
    name: "Ukraine",
    dial_code: "+380",
    code: "UA",
    ccode: "380",
    show: "UA(+380)",
  },
  {
    name: "United Arab Emirates",
    dial_code: "+971",
    code: "AE",
    ccode: "971",
    show: "AE(+971)",
  },
  {
    name: "United Kingdom",
    dial_code: "+44",
    code: "GB",
    ccode: "44",
    show: "GB(+44)",
  },
  {
    name: "United States",
    dial_code: "+1",
    code: "US",
    ccode: "1",
    show: "US(+1)",
  },
  {
    name: "Uruguay",
    dial_code: "+598",
    code: "UY",
    ccode: "598",
    show: "UY(+598)",
  },
  {
    name: "Uzbekistan",
    dial_code: "+998",
    code: "UZ",
    ccode: "998",
    show: "UZ(+998)",
  },
  {
    name: "Vanuatu",
    dial_code: "+678",
    code: "VU",
    ccode: "678",
    show: "VU(+678)",
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    dial_code: "+58",
    code: "VE",
    ccode: "58",
    show: "VE(+58)",
  },
  {
    name: "Vietnam",
    dial_code: "+84",
    code: "VN",
    ccode: "84",
    show: "VN(+84)",
  },
  {
    name: "Virgin Islands, British",
    dial_code: "+1284",
    code: "VG",
    ccode: "1284",
    show: "VG(+1284)",
  },
  {
    name: "Virgin Islands, U.S.",
    dial_code: "+1340",
    code: "VI",
    ccode: "1340",
    show: "VI(+1340)",
  },
  {
    name: "Wallis and Futuna",
    dial_code: "+681",
    code: "WF",
    ccode: "681",
    show: "WF(+681)",
  },
  {
    name: "Yemen",
    dial_code: "+967",
    code: "YE",
    ccode: "967",
    show: "YE(+967)",
  },
  {
    name: "Zambia",
    dial_code: "+260",
    code: "ZM",
    ccode: "260",
    show: "ZM(+260)",
  },
  {
    name: "Zimbabwe",
    dial_code: "+263",
    code: "ZW",
    ccode: "263",
    show: "ZW(+263)",
  },
];
